name: Bug Report
description: File a bug report
type: Bug
assignees:
  - Classsic36
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "Example: The Soul Lantern item sprite does not have its updated texture."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of Classic's Lantern Tweaks are you using? If it's not listed, please consider updating!
      options:
        - v2.3.0-pre.1
        - v2.2.0
    validations:
      required: true
  - type: textarea
    id: mcversion
    attributes:
      label: Minecraft Version
      description: Which version of Minecraft are you using?
      placeholder: Simply "26.1.2" or "26.2 Snapshot 8", for example, will do.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please upload any relevant logs to https://mclo.gs/ and paste the link here.
    validations:
      required: false